tests of the EngageSphere application.
wlsf82/EngageSphere-Test-Design-Masterclass-TAT pull request #7
Opened 2024-05-16 03:13 UTC by jonathanrsbr

Tests performed by Jonathan Sales:

- API (Success and Invalid requests tests);

- Accessibility tests;

- GUI Component tests.

2024-05-16 18:03 UTC, wlsf82 requested changes
Bom trabalho @jonathanrsbr! 👏🏻 

Além das sugestões e comentários, aqui vão mais algumas considerações.

A idéia era implementar testes, e devido as configurações de ESLint, você acabou mudando o código da aplicação inteira.
Já havia uma padrão, e este, não deveria ter sido alterado, mas sim, seguido.

Além disso, vejo que você usou a convenção de commits semânticos, no entanto, usou `feat` para vários commits que deveriam ser `test`.

Por fim, não consegui rodar os testes de componentes no seu branch main.

A Cypress App exibe o seguinte erro:

```
Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

...

Error: Failed to find webpack at /Users/walmyr/workspaces/jonathanrsbr/EngageSphere-Test-Design-Masterclass-TAT/config/webpack.config.js. We looked in this location as we could not find the "react-scripts" dependency and are assuming an ejected create-react-app.
    at loadWebpackConfig (/Users/walmyr/Library/Caches/Cypress/13.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/createReactAppHandler.js:53:19)
    at createReactAppHandler (/Users/walmyr/Library/Caches/Cypress/13.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/createReactAppHandler.js:18:27)
    at getPreset (/Users/walmyr/Library/Caches/Cypress/13.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:86:70)
    at devServer.create ...

```

Espero que o feedback seja útil para as próximas melhorias.

2024-05-16 18:03 UTC, wlsf82 commented on .gitignore
> +# sensitive files
Só o `cypress.env.json` é um arquivo com dados sensíveis, as pastas são só artefatos de testes que não devem ser versionados, e portanto, o comentário confunde o que está abaixo dele.

2024-05-16 18:03 UTC, wlsf82 commented on .prettierignore
> +screenshots
```suggestion
screenshots

```

É uma boa prática deixar uma linha em branco ao final de cada arquivo.

2024-05-16 18:03 UTC, wlsf82 commented on README.md
> +- Installation and tests
Que tal

```suggestion
### Installation
```

2024-05-16 18:03 UTC, wlsf82 commented on README.md
> +Install the dev dependencies: run `npm install` (or `npm i` for the short version)
E

```suggestion
To install the dev dependencies, run `npm install` (or `npm i` for the short version.)
```

2024-05-16 18:03 UTC, wlsf82 commented on README.md
> +
```suggestion
### Running the tests
```

2024-05-16 18:03 UTC, wlsf82 commented on README.md
> +Test in headless mode: run `npm test` (or `npm t` for the short version)
```suggestion
To test in headless mode, run `npm test` (or `npm t` for the short version.)
```

2024-05-16 18:03 UTC, wlsf82 commented on README.md
> +Test in interactive mode: run `npm run cy:open`
```suggestion
To test in interactive mode: run `npm run cy:open`.
```

2024-05-16 18:03 UTC, wlsf82 commented on cypress.config.js
> +const { defineConfig } = require('cypress')
Muitas espaços para a indentação, não acha?

Dois espaços por nível já são o suficiente, além de diminuirem a chance de _scroll_ horizontal.

> O mesmo vale para os outros arquivos.

2024-05-16 18:03 UTC, wlsf82 commented on cypress.config.js
> +
```suggestion
```

2024-05-16 18:03 UTC, wlsf82 commented on cypress/e2e/accessibility/Accessibility.cy.js
> +})
Interessante abordagem! 👍🏻

2024-05-16 18:03 UTC, wlsf82 commented on cypress/e2e/api/EngageSphere.cy.js
> +	context('Successful request', () => {
```suggestion
	context('Successful requests', () => {
```

2024-05-16 18:03 UTC, wlsf82 commented on cypress/e2e/api/EngageSphere.cy.js
> +				expect(body.customers).to.be.an('array').that.is.not.empty
👍🏻

2024-05-16 18:03 UTC, wlsf82 commented on cypress/e2e/api/EngageSphere.cy.js
> +				expect(status).to.eq(200)
Que tal remover estas verificações, já feitas no teste anterior, e neste focar só no que vem na propriedade `pageInfo`?

2024-05-16 18:03 UTC, wlsf82 commented on cypress/e2e/api/EngageSphere.cy.js
> +				expect(pageInfo.totalCustomers).to.be.gte(50)
Aqui não deveria ser **less than or equal**? (`.to.be.lte(50)`)?

```suggestion
				expect(pageInfo.totalCustomers).to.be.lte(50)
```

2024-05-16 18:03 UTC, wlsf82 commented on cypress/e2e/api/EngageSphere.cy.js
> +					expect(customer.employees).to.be.at.least(100).and.to.be.below(1000)
👍🏻

2024-05-16 18:03 UTC, wlsf82 commented on cypress/e2e/api/EngageSphere.cy.js
> +		})
Que tal também testar páginas e limite = 0?

E uma página vazia? Ex.: `?page=6&limit=10`

2024-05-16 18:03 UTC, wlsf82 commented on cypress/e2e/gui/Gui.cy.js
> +describe('template spec', () => {
❓

2024-05-16 18:03 UTC, wlsf82 commented on cypress/support/accessibility_commands.js
> +Cypress.Commands.add('accessibilityCheck', ({ mode = 'light', showDetails = false, showAddress = false } = {}) => {
Apesar de interessante no contexto do teste, aqui achei bem confuso.

2024-05-16 18:03 UTC, wlsf82 commented on cypress/support/e2e.js
> +import './accessibility_commands'
Deixe um espaço em branco entre módulos externos e internos.

Isso facilita identificar o que é o que.

```suggestion
import './accessibility_commands'

```

2024-05-21 13:38 UTC, aleksonfortes commented
Mano, muito top o teu trabalho! Voce deveria revisar o meu codigo e nao eu o seu... rsrs
A unica coisa que eu encontrei que eu faria diferente, eh: 
Ao inves de usar feat pra testes, eu usaria test. No teu conventional commit messages.
Fora isso, parabens, excelente trabalho!

2024-05-23 04:45 UTC, jonathanrsbr commented on cypress/e2e/api/EngageSphere.cy.js
> +		})
Percebi que o segundo teste (Ex: page: 6, limit: 10), provavelmente era para retornar  um status 400, de BAD REQUEST, com uma mensagem "Invalid page or limit. Both must be positive numbers.",  ou alguma mensagem semelhante, porém retornou 200 e uma Response com "customers": []. É normal?

2024-05-23 04:51 UTC, jonathanrsbr commented on cypress/support/accessibility_commands.js
> +Cypress.Commands.add('accessibilityCheck', ({ mode = 'light', showDetails = false, showAddress = false } = {}) => {
Obrigado pelo feedback, tentarei otimizar os testes de acessibilidade no próximo round.

2024-05-24 04:25 UTC, jonathanrsbr commented on cypress/e2e/api/EngageSphere.cy.js
> +		})
![Screenshot 2024-05-24 012338](https://github.com/wlsf82/EngageSphere-Test-Design-Masterclass-TAT/assets/105602767/07bb9016-8ceb-4baa-99c9-bdd69632c4cb)

2024-05-24 17:52 UTC, wlsf82 requested changes
Excelente trabalho @jonathanrsbr! 👏🏻 

Deixei mais alguns comentários, com os quais creio que vai ficar 🔝.

2024-05-24 17:52 UTC, wlsf82 commented on .github/workflows/ci.yml
> +      - name: Set up Node.js
Não vejo a necessidade disso, visto que a image `cypress-io/github-action@v6` já possui o Node.js instalado.
Inclusive, tal imagem já vem com o Node 20.

Ref.: https://github.com/cypress-io/github-action?tab=readme-ov-file#compatibility

2024-05-24 17:52 UTC, wlsf82 commented on .github/workflows/ci.yml
> +      - name: Start backend server
Outra alternativa seria o step `Run Cypress tests` ter o seguinte antes do `start`, abaixo do `with:`

`start: npm run start:frontend, npm run start:server`

2024-05-24 17:52 UTC, wlsf82 commented on .gitignore
> +cypress/videos/
Que tal não versionar também a pasta `cypress/downloads/`?

2024-05-24 17:52 UTC, wlsf82 commented on README.md
> +Tested by [Jonathan Sales](https://www.linkedin.com/in/jonathan-sales-44580b1b3/).
❤️

2024-05-24 17:52 UTC, wlsf82 commented on cypress/downloads/customers.csv
> +ID,Company_Name,Number_of_Employees,Size,Contact_Name,Contact_Email,Street,City,State,Zip_Code,Country
Este arquivo não deveria ser versionado, visto que é um artefato gerado após a execução dos testes.

2024-05-24 17:52 UTC, wlsf82 commented on cypress/e2e/api/EngageSphere.cy.js
> +          expect(customer.employees).to.be.at.least(100).and.to.be.below(1000)
❤️

2024-05-24 17:52 UTC, wlsf82 commented on cypress/support/accessibility_commands.js
> +Cypress.Commands.add('accessibilityCheck', ({ mode = 'light', showDetails = false, showAddress = false } = {}) => {
Resolveu deixar assim?

2024-05-24 17:52 UTC, wlsf82 commented on cypress/support/api_commands.js
> +Cypress.Commands.add('api_getCustomers', ({ page = 1, limit = 10, size = 'All', failOnStatusCode = true } = {}) => {
👍🏻

2024-05-24 17:52 UTC, wlsf82 commented on cypress/support/api_commands.js
> +    failOnStatusCode: failOnStatusCode
Quando do parâmetro/variável tem o mesmo nome do propriedade, este pode ser omitido.

```suggestion
    failOnStatusCode
```

2024-05-24 17:52 UTC, wlsf82 commented on cypress/support/e2e.js
> +import 'cypress-axe'
Que tal organizar _libs_ externas em ordem alfabética. Só uma sugestão de uma convenção que vejo projetos usando.

2024-05-24 17:52 UTC, wlsf82 commented on frontend/package.json
> +    "cypress": "^13.9.0",
Saiu a v13.10.0! 🎉

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/CustomerDetails.cy.js
> +const customerWithoutContactInfo = {
A propósito, você poderia definir um único customer (com todas as informações) e sobrescrever `contactInfo` e/ou `address` para `null`.

Veja um exemplo:

```js
const customerWithoutContactInfo = {
  ...completeCustomer,
  contactInfo: null,
}
```

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/CustomerDetails.cy.js
> +    cy.get('.customer-details p').contains(`Contact name: ${customer.contactInfo.name}`).should('be.visible')
Que tal algo assim?

```suggestion
    cy.contains('p', `Contact name: ${customer.contactInfo.name}`).should('be.visible')
```

Essa format é mais robusta, visto como o Cypress trabalha com retentativas.

> O mesmo vale para as próximas verificações.

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/CustomerDetails.cy.js
> +  })
É uma boa prática deixar uma linha em branco entre blocos `it`.

Chamo isso de "deixar o código respirar". 😄

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/CustomerDetails.cy.js
> +  it('Hides customer address', () => {
Que tal juntar este e o teste anterior em um só (ex.:`Shows and hides the customer's address`)?

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/CustomerDetails.cy.js
> +    const onClickMock = cy.stub()
Que tal?

```suggestion
    const onClickStub = cy.stub()
```

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/CustomerDetails.cy.js
> +    cy.get('button').contains('Back').click()
Conforme comentei na aula sobre níveis de teste, seria uma melhor abordagem (por questões de cobertura de funcionalidade) testar tal cenário em um teste mais integrado. Testar que uma função _stub_ foi chamada não trás grande benefícios neste caso.

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/DownloadCSV.cy.js
> +const customers = [
Que tal mover isso para `cypress/fixtures/` e importar aqui?

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/DownloadCSV.cy.js
> +describe('DownloadCSVButton component', () => {
Veja uma solução simplificada para o mesmo teste:

```js
import DownloadCSV from './DownloadCSV.js'

const customers = require('../../../cypress/fixtures/customers.json').customers
const sampleCSV = require('../../../cypress/fixtures/sampleCSV.js')

describe('<DownloadCSV />', () => {
  it('correctly downloads a list of customers as a CSV file', () => {
    cy.mount(<DownloadCSV customers={customers} />)

    cy.contains('button', 'Download CSV').click()

    cy.readFile('cypress/downloads/customers.csv').should('be.equal', sampleCSV)
  })
})
```

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/EmptyState.cy.js
> +describe('EmptyState component', () => {
Este é outro comportamento que eu daria preferência por um nível de teste integrado, para garantir que quando não há clientes no banco de dados, tal imagem componente é realmente exibido.

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Footer.cy.js
> +    cy.get('[data-testid="footer"]').contains('Copyright 2024 - Talking About Testing').should('be.visible')
Em vez de `cy.get('seletor').contains('conteúdo')`, se acostume a usar `cy.contains('seletor', 'conteúdo')`.

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Footer.cy.js
> +    cy.get('[data-testid="footer"] a').eq(0).should('have.attr', 'href', 'https://udemy.com/user/walmyr')
Que tal algo assim?

```js
cy.contains('a', 'Udemy')
  .should('be.visible')
  .and('have.attr', 'href', 'https://udemy.com/user/walmyr')
```

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Greeting.cy.js
> +  })
```suggestion
  })
  
```

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Greeting.cy.js
> +    cy.get('p').first().should('have.text', `Hi there! It is now ${new Date().toDateString()}.`)
Outra alternativa seria congelar o relógio do navegador usando o comando `cy.clock()`.

Veja um exemplo:

```js
import React from 'react'
import Greeting from './Greeting'

describe('<Greeting />', () => {
  beforeEach(() => {
    const now = new Date(2024, 3, 15) // month is 0-indexed
    cy.clock(now)
  })

  it('renders "Hi there" when no name is provided', () => {
    cy.mount(<Greeting />)

    cy.contains('p', 'Hi there! It is now Mon Apr 15 2024.')
      .should('be.visible')
  })

  it('renders "Hi Joe" when name is provided', () => {
    cy.mount(<Greeting name='Joe' />)

    cy.contains('p', 'Hi Joe! It is now Mon Apr 15 2024.')
      .should('be.visible')
  })
})

```

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Input.cy.js
> +    cy.mount(<Input customers={emptyCustomers} />)
Eu faria só `cy.mount(<Input customers={[]} />)`.

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Input.cy.js
> +    const customer = { id: 1, name: 'Jon S.A.', employees: 10, size: 'small' }
Caso houvessem _customers_ em `cypress/fixtures/`, este poderia estar vindo de lá. 🤔

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Pagination.cy.js
> +      cy.get('button').contains('Prev').should('be.disabled')
Eu não usaria o `.within` aqui.

Faria só: `cy.contains('button', 'Prev').should('be.disabled').and('be.visible')`

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Pagination.cy.js
> +      cy.get('button').contains('Prev').should('be.disabled')
> O mesmo vale para os outros testes desta suite.

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Pagination.cy.js
> +  })
Sem linhas em branco entre os testes, fica tudo muito amontoado.

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Pagination.cy.js
> +        onChange={() => {
Aqui devia ser um `cy.stub`.

Não tem pq você implementar o que o _frontend_ deveria implementar, pois dessa forma, você testa sua implementação, não o _front_.

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Pagination.cy.js
> +    cy.get('[data-testid="pagination"] select').select('50')
Seria interessante verificar depois da seleção, que tal valor foi persistido no `select`.

Algo como: `cy.get('select').should('have.value', 50)`

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/SizeFilter.cy.js
> +      cy.get('[data-testid="filter"]').select(size)
Eu deixaria um espaço em branco entre _Act_ e _Assert_.

```suggestion
      cy.get('[data-testid="filter"]').select(size)
      
```

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Table.cy.js
> +        cy.get('tbody').contains('td', customer.id).should('be.visible')
Use só o `cy.contains` conforme já comentado em outros comentários.

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Table.cy.js
> +    it.only('Sorts by Number of employees in ascending order', () => {
```suggestion
    it('Sorts by Number of employees in ascending order', () => {
```

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Table.cy.js
> +      cy.get('tbody tr').first().find('td').eq(2).should('contain', '50')
Que tal verificar o `.last` também?

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Table.cy.js
> +      cy.get('tbody tr').first().find('td').eq(2).should('contain', '50')
> O mesmo vale para outros testes dessa suite.

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/Table.cy.js
> +      cy.mount(<App />)
Esta suite é do componente `<Table />`, portanto, testar o <App /> não parece adequado.

Eu deixaria este para um teste de GUI, onde utilizaria o `cy.intercept` sobrescrevendo o `delay` da requisição, para testar tal estado transitório de forma controlada e robusta.

2024-05-24 17:52 UTC, wlsf82 commented on frontend/src/components/ThemeToggle.cy.js
> +      win.localStorage.setItem('theme', 'dark')
👍🏻

2024-05-24 18:11 UTC, jonathanrsbr commented on .gitignore
> +cypress/videos/
Bem lembrado, pensei, mas na versão final acabei esquecendo. Obrigado!

2024-05-24 19:25 UTC, jonathanrsbr commented on frontend/src/components/DownloadCSV.cy.js
> +const customers = [
Estava pensando nisso, mas pelo desejo de terminar todos os testes, algumas perguntas passaram em branco, aguardava esse feedback mesmo! (Então não é uma má prática usar fixtures em testes de componente! Aplicarei a lógica para outros também.)  Obrigado

2024-06-10 22:29 UTC, wlsf82 commented
Estou fechando este PR visto o fim da turma 1 da _Test Design Masterclass_.

2024-06-10 22:29 UTC, closed without merging