EngageSphere - Tests
wlsf82/EngageSphere-Test-Design-Masterclass-TAT pull request #8
Opened 2024-05-16 05:53 UTC by L4nd1m

EU TENTEEEEI fazer um commit pra cada mudança, mas tal hora me empolguei e acabei acumulando muita coisa. vou melhorar na próxima ;)

2024-05-16 19:17 UTC, wlsf82 requested changes
Bom trabalho @L4nd1m! 👏🏻 

No entanto, deixei uma série de comentários e sugestões com diversos pontos de melhorias.

Espero que o feedback seja útil para o próximo _round_ de _review_.

2024-05-16 19:17 UTC, wlsf82 commented on README.md
> +to run the API test : npm run test:api
```suggestion
To run the API tests, `npm run test:api`.
```

2024-05-16 19:17 UTC, wlsf82 commented on README.md
```suggestion

### Running the tests
```

2024-05-16 19:17 UTC, wlsf82 commented on README.md
> +to run the accessibility test: npm run test:a11y
```suggestion
To run the accessibility test, `npm run test:a11y`.
```

2024-05-16 19:17 UTC, wlsf82 commented on README.md
> +to run the component tests : didn't found out yet :( (I was running
`To run the component tests, ...`

2024-05-16 19:17 UTC, wlsf82 commented on cypress.config.js
> +
```suggestion
```

Não adicione linhas em branco desnecessárias, isso só aumenta o número de linhas do arquivo, sem reais benefícios de legibilidade.

2024-05-16 19:17 UTC, wlsf82 commented on cypress/e2e/a11y/a11yCustomers.cy.js
> +
```suggestion
```

2024-05-16 19:17 UTC, wlsf82 commented on cypress/e2e/a11y/a11yCustomers.cy.js
> +    it('mostrar endereço -> não encontra problemas de acessibilidade no modo claro', () => {
Que tal criar um `context` para `Mostrar endereço`, com seu próprio `beforeEach`, evitando repetir os primeiros passos em ambos os testes?

2024-05-16 19:17 UTC, wlsf82 commented on cypress/e2e/a11y/a11yCustomers.cy.js
> +    it('não encontra problemas de acessibilidade no modo claro', () => {
Que tal criar um `context` para `Customer details`, com seu próprio `beforeEach`, evitando os primeiros dois passos repetidos em ambos os testes?

2024-05-16 19:17 UTC, wlsf82 commented on cypress/e2e/api/getCustomers.cy.js
> +
```suggestion
```

2024-05-16 19:17 UTC, wlsf82 commented on cypress/e2e/api/getCustomers.cy.js
> +})
Que tal cenários para páginas e limite = 0?

E também para página vazia? Ex.: `?page=6&limit=10`.

2024-05-16 19:17 UTC, wlsf82 commented on cypress/fixtures/customers.js
> +const listavazia = [
Não vejo vantagen alguma em abstrair um array vazio. Isso usa muito mais caracteres do que simplesmente escrever `[]`.

2024-05-16 19:17 UTC, wlsf82 commented on cypress/fixtures/download.csv
> +ID,Company_Name,Number_of_Employees,Size,Contact_Name,Contact_Email,Street,City,State,Zip_Code,Country\n"undefined","Kohler LLC","87549","Very Large Enterprise","Lera","Lera75@hotmail.com","1715 Ches
Ao executar o teste `frontend/src/components/DownloadCSV.cy.js`, o mesmo falha com o seguinte erro:

```
assert expected
ID,Company_Name,Number_of_Employees,Size,Contact_Name,Contact_Email,Street,City,State,Zip_Code,Country\n"1","Kohler LLC","87549","Small","Lera","Lera75@hotmail.com","1715 Chestnut Drive","Fond du Lac","Oregon","43394-9212","United States of America"\n"2","Lowe Co","50000","Very Large Enterprise","","","87908 Adkins Islands Apt. 944","West Sarah","Georgia","79943","United States of America"\n"3","Rempel Inc","54642","Very Large Enterprise","","","","","","",""
to include
ID,Company_Name,Number_of_Employees,Size,Contact_Name,Contact_Email,Street,City,State,Zip_Code,Country\\n"undefined","Kohler LLC","87549","Very Large Enterprise","Lera","Lera75@hotmail.com","1715 Chestnut Drive","Fond du Lac","Oregon","43394-9212","United States of America"\\n"undefined","Lowe Co","50000","Very Large Enterprise","","","87908 Adkins Islands Apt. 944","West Sarah","Georgia","79943","United States of America"\\n"undefined","Rempel Inc","54642","Very Large Enterprise","","","","","","",""

```

2024-05-16 19:17 UTC, wlsf82 commented on cypress/fixtures/download.csv
> +ID,Company_Name,Number_of_Employees,Size,Contact_Name,Contact_Email,Street,City,State,Zip_Code,Country\n"undefined","Kohler LLC","87549","Very Large Enterprise","Lera","Lera75@hotmail.com","1715 Ches
Parece um problema de quebra de linha.

2024-05-16 19:17 UTC, wlsf82 commented on cypress/fixtures/emptyTable.js
> +const emptyTable = []
Já comentei sobre isso.

2024-05-16 19:17 UTC, wlsf82 commented on cypress/support/e2e.js
> +import 'cypress-axe'
Recomendo mover libs externas para o topo e separar de módulos internos com uma linha em branco.
Dessa forma, fica simples saber o que é o que.
Além disso, recomendo deletar os comentários gerados automaticamente ao criar um projeto com Cypress.

2024-05-16 19:17 UTC, wlsf82 commented on cypress/support/e2e.js
> +// require('./commands')
```suggestion
// require('./commands')

```

É uma boa prática deixar uma linha em branco ao final de cada arquivo.

2024-05-16 19:17 UTC, wlsf82 commented on frontend/cypress/support/component.js
> +import Customers from '../../../cypress/fixtures/customers';
Onde essa linha é usada neste arquivo?
O mesmo vale para a linha abaixo.

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/CustomerDetails.cy.js
> +        cy.contains('.customer-details', 'Contact email').should('be.visible')
Que tal verificar os valores sendo renderizados para o cliente, não só os labels?

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/CustomerDetails.cy.js
> +        cy.contains('.address-info', 'Country').should('be.visible')
O mesmo que o comentário anterior, mas para as informações de endereço.

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/CustomerDetails.cy.js
> +    it.skip('Volta para a lista de clientes ao clicar no botão "Voltar"', () => {
Deletar daqui então.

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/DownloadCSV.cy.js
> +      cy.readFile('cypress/downloads/customers.csv').should('exist').and('contain', content)
Teste falhando devido a problema de quebra de linha, conforme comentado anteriormente.

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/Footer.cy.js
> +    cy.contains('a', 'Udemy').should('be.visible').and('have.attr', 'href', 'https://udemy.com/user/walmyr')
Que tal quebrar linhas, para ajudar na legibilidade?

Ex.:

```js
cy.contains('a', 'Udemy')
  .should('be.visible')
  .and('have.attr', 'href', 'https://udemy.com/user/walmyr')

```

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/Greeting.cy.js
> +})
```suggestion
})

```

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/Greeting.cy.js
> +    cy.contains('p', 'Hi Joe! It is now Thu May 16 2024.').should('be.visible')
👍🏻

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/Input.cy.js
> +    cy.mount(<Input customers={emptyTable} />)
Aqui podeia ser simplesmente `cy.mount(<Input customers={[]} />)`

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/Pagination.cy.js
> +    cy.mount(<Pagination currentPage={parseInt(pageInfo.currentPage)} paginationInfo={pageInfo} defaultProps />)
Que tal separar a variável, o `mount` e as verificações por uma linha em branco, para facilitar o entendimento do que é pré-condição, ação e resultado esperado?

> O mesmo vale para outros testes.

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/Pagination.cy.js
> +  })
```suggestion
  })
  
```

Entre _test cases_ vale a pena deixar uma linha em branco. Isso facilita a legibilidade.

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/Pagination.cy.js
> +    window.localStorage.setItem('limit', novoLimite)
Aqui vai outra alternativa:

```js
cy.getAllLocalStorage()
  then((result) => {
    const limit = result[Cypress.config('baseUrl')].paginationLimit
    expect(limit).to.equal('20')
  })

```

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/SizeFilter.cy.js
> +describe('<SizeFilter />', () => {
Não vejo vantagem em testar tal situação à nível de componente.

Isso testa o comportamento do navegador, não da aplicação.

Para filtragem, eu diria que testes de API e de GUI que garantam que o _request_ correto é disparado já seriam o suficiente.

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/Table.cy.js
> +  it.skip('Pega elemento de loading', () => {
Não fazer commit de testes sendo `.skip`ped.

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/Table.cy.js
> +  it('Ordena por Número de funcionários em ordem ascendente', () => {
Veja abaixo um exemplo meu de um teste dos comportamentos de ordenação para o componente `<Table />`.

```js
import Table from './Table'

const customers = require('../../../cypress/fixtures/customers.json').customers

it('sorts by Number of employees in ascending order', () => {
  cy.mount(<Table customers={customers} customerClickHandler={cy.stub()} />)

  cy.contains('th', 'Number of employees').click()
  cy.contains('th', 'Number of employees').click()
  cy.contains('th', 'Number of employees ↑').should('be.visible')
  cy.get('tbody tr')
    .first()
    .find('td')
    .eq(2)
    .should('contain', '47')

  cy.get('tbody tr')
    .last()
    .find('td')
    .eq(2)
    .should('contain', '51015')
})

```

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/Table.cy.js
> +  it('Ordena por Número de funcionários em ordem ascendente', () => {
Percebe a simplicidade, sem a necessidade de cálculos, como `Customers.length - 1`?
E sem a necessidade de `parseInt`...

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/ThemeToggler.cy.js
> +    // see: https://on.cypress.io/mounting-react
```suggestion
```

2024-05-16 19:17 UTC, wlsf82 commented on frontend/src/components/ThemeToggler.cy.js
> +    cy.get('#theme-toggle-button').click()
Na documentação oficial do comando `cy.click()` (https://docs.cypress.io/api/commands/click), é comentado o seguinte:

_It is [unsafe](https://docs.cypress.io/guides/core-concepts/retry-ability#Only-queries-are-retried) to chain further commands that rely on the subject after .click()._

Recomendo re-pensar essa verificação.

2024-05-16 19:17 UTC, wlsf82 commented on package.json
> +  "name": "engagesphere-test-design-masterclass-tat",
Por qual motivo mudar o nome do projeto?

2024-05-16 21:41 UTC, L4nd1m commented on frontend/src/components/CustomerDetails.cy.js
> +    it.skip('Volta para a lista de clientes ao clicar no botão "Voltar"', () => {
mas eu ainda pretendo fazer

2024-05-16 21:48 UTC, L4nd1m commented on package.json
> +  "name": "engagesphere-test-design-masterclass-tat",
Eu sinceramente não sei como isso aconteceu. Não mexi no nome do projeto

2024-06-10 22:29 UTC, wlsf82 commented
Estou fechando este PR visto o fim da turma 1 da _Test Design Masterclass_.

2024-06-10 22:29 UTC, closed without merging